import {useEffect,useMemo,useState} from 'react'
import {motion,AnimatePresence} from 'framer-motion'
import {Activity,Boxes,ChevronRight,CircleGauge,Cloud,Command,Cpu,Database,GitBranch,Globe2,HardDrive,LayoutDashboard,Moon,Rocket,Search,Server,Settings,ShieldCheck,Sun,TerminalSquare,Users,X,Zap} from 'lucide-react'
import {AreaChart,Area,BarChart,Bar,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'
import {projects,deployments,traffic,events} from './data'

const nav=[['overview','Overview',LayoutDashboard],['projects','Projetos',Boxes],['deployments','Deployments',Rocket],['analytics','Analytics',Activity],['settings','Settings',Settings]]
const tip={background:'#0b1725',border:'1px solid #20364b',borderRadius:8,fontSize:12}
function Status({value}){const c=value.toLowerCase().replace(' ','-');return <span className={'status status-'+c}><i/>{value}</span>}
function Stat({icon:Icon,label,value,detail}){return <motion.article className="stat" whileHover={{y:-3}}><div className="statIcon"><Icon size={18}/></div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></motion.article>}
function Traffic(){return <ResponsiveContainer width="100%" height={260}><AreaChart data={traffic}><defs><linearGradient id="a" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#7fd2ff" stopOpacity=".3"/><stop offset="100%" stopColor="#7fd2ff" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#12263a" strokeDasharray="3 6"/><XAxis dataKey="time" stroke="#547089" axisLine={false} tickLine={false}/><YAxis stroke="#547089" axisLine={false} tickLine={false}/><Tooltip contentStyle={tip}/><Area type="monotone" dataKey="requests" stroke="#7fd2ff" fill="url(#a)" strokeWidth={2}/></AreaChart></ResponsiveContainer>}
function Builds(){return <ResponsiveContainer width="100%" height={240}><BarChart data={traffic}><CartesianGrid stroke="#12263a" strokeDasharray="3 6"/><XAxis dataKey="time" stroke="#547089" axisLine={false} tickLine={false}/><YAxis stroke="#547089" axisLine={false} tickLine={false}/><Tooltip contentStyle={tip}/><Bar dataKey="builds" fill="#7fd2ff" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer>}
function Palette({close,setPage}){const[q,setQ]=useState('');const opts=useMemo(()=>nav.filter(x=>x[1].toLowerCase().includes(q.toLowerCase())),[q]);return <motion.div className="overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={e=>e.target===e.currentTarget&&close()}><motion.div className="palette" initial={{scale:.96,y:-10}} animate={{scale:1,y:0}}><div className="palInput"><Command size={18}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Ir para uma área…"/><button onClick={close}><X size={17}/></button></div><div className="palList">{opts.map(([id,label,Icon])=><button key={id} onClick={()=>{setPage(id);close()}}><Icon size={17}/><span>{label}</span><kbd>↵</kbd></button>)}</div></motion.div></motion.div>}
function Shell({page,setPage,dark,setDark,children}){const[palette,setPalette]=useState(false);useEffect(()=>{const f=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(v=>!v)}};addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[]);return <div className={'app '+(dark?'dark':'light')}><aside className="sidebar"><div className="brand"><div className="mark">Z</div><div><b>ZTR</b><span>OPS NEXUS</span></div></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon size={17}/><span>{label}</span><ChevronRight size={14}/></button>)}</nav><div className="foot"><span className="pulse"/><div><b>Armbian</b><small>Control plane online</small></div></div></aside><main><header className="topbar"><div><span className="eyebrow">ZTR COMPANY / CONTROL PLANE</span><h1>{nav.find(x=>x[0]===page)?.[1]}</h1></div><div className="actions"><button className="search" onClick={()=>setPalette(true)}><Search size={16}/><span>Pesquisar</span><kbd>Ctrl K</kbd></button><button className="icon" onClick={()=>setDark(v=>!v)}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button><div className="avatar">JC</div></div></header><div className="content">{children}</div></main><AnimatePresence>{palette&&<Palette close={()=>setPalette(false)} setPage={setPage}/>}</AnimatePresence></div>}
function Head({over,title,button}){return <div className="head"><div><span className="eyebrow">{over}</span><h3>{title}</h3></div>{button}</div>}
function Overview(){return <div className="grid"><section className="hero"><div><span className="eyebrow">INFRASTRUCTURE STATUS</span><h2>Todos os sistemas nominais.</h2><p>Sites, APIs, builds e banco dentro da faixa esperada.</p></div><div className="health"><span>99.98%</span><small>uptime / 30 dias</small></div></section><div className="stats"><Stat icon={Globe2} label="Sites online" value="18" detail="+3 neste mês"/><Stat icon={Rocket} label="Deploys hoje" value="46" detail="94% aprovados"/><Stat icon={Cpu} label="CPU média" value="27%" detail="pico 61%"/><Stat icon={HardDrive} label="Storage" value="8.4 GB" detail="de 31.3 GB"/></div><section className="panel chart"><Head over="TRÁFEGO" title="Requests nas últimas 24 horas"/><Traffic/></section><section className="panel events"><Head over="EVENT STREAM" title="Atividade recente"/>{events.map(([t,a,b],i)=><div className="event" key={i}><i/><div><b>{a}</b><small>{b}</small></div><time>{t}</time></div>)}</section><section className="panel services"><Head over="SERVICES" title="Core ZTR"/><div className="serviceGrid">{[['ZTR Site Hosting','4181',Globe2],['ZTR Cloud','3100',Database],['Backend Cloud','API',Server],['Cloudflare Tunnel','Edge',Cloud]].map(([n,p,I])=><div className="service" key={n}><I size={18}/><div><b>{n}</b><small>{p}</small></div><Status value="Live"/></div>)}</div></section></div>}
function Projects(){const[f,setF]=useState('Todos');const shown=projects.filter(p=>f==='Todos'||p.status===f);return <><div className="toolbar"><div className="tabs">{['Todos','Live','Building','Review'].map(x=><button key={x} className={f===x?'active':''} onClick={()=>setF(x)}>{x}</button>)}</div><button className="primary"><Rocket size={15}/>Novo projeto</button></div><div className="projectGrid">{shown.map((p,i)=><motion.article className="project" key={p.name} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:i*.04}}><div className="projectTop"><div className="logo">{p.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><Status value={p.status}/></div><h3>{p.name}</h3><span className="kind">{p.type}</span><div className="progress"><i style={{width:p.progress+'%'}}/></div><div className="meta"><span><b>{p.progress}%</b>progresso</span><span><b>{p.reach}</b>alcance</span><span><b>{p.deploy}</b>deploy</span></div></motion.article>)}</div></>}
function Deployments(){return <section className="panel table"><Head over="RELEASE PIPELINE" title="Últimos deployments" button={<button className="primary"><Rocket size={15}/>Deploy</button>}/><div className="rows"><div className="row th"><span>ID</span><span>Projeto</span><span>Git</span><span>Status</span><span>Duração</span><span>Autor</span></div>{deployments.map(d=><div className="row" key={d.id}><code>{d.id}</code><b>{d.project}</b><span><GitBranch size={13}/>{d.branch} · <code>{d.commit}</code></span><Status value={d.status}/><span>{d.duration}</span><span>{d.author}</span></div>)}</div></section>}
function Analytics(){const log=['14:46:05 clone repository mirror refreshed','14:46:06 detect React + Vite','14:46:06 install npm ci','14:46:18 build npm run build','14:46:22 output dist/','14:46:23 health 200 OK','14:46:23 release promoted atomically','14:46:23 status LIVE'].join('\n');return <div className="analytics"><section className="panel wide"><Head over="BUILD LOAD" title="Execuções por janela"/><Builds/></section><section className="panel metrics"><h3>Performance</h3>{[['P95 latency','48 ms',Zap],['Cache hit','91.7%',CircleGauge],['Active users','2,408',Users],['Protected routes','37',ShieldCheck]].map(([a,b,I])=><div className="metric" key={a}><I size={18}/><span>{a}</span><b>{b}</b></div>)}</section><section className="panel terminal"><div className="termHead"><TerminalSquare size={17}/><span>build.log</span><i/></div><pre>{log}</pre></section></div>}
function SettingsPage(){const[keep,setKeep]=useState(5),[auto,setAuto]=useState(true);return <div className="settingsGrid"><section className="panel form"><span className="eyebrow">BUILD POLICY</span><h3>Deployment defaults</h3><label>Releases mantidas<input type="number" value={keep} onChange={e=>setKeep(e.target.value)} min="1" max="30"/></label><label>Branch padrão<input value="main" readOnly/></label><label className="check"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/><span><b>Auto Deploy</b><small>Iniciar build após push</small></span></label><button className="primary">Salvar configurações</button></section><section className="panel security"><ShieldCheck size={28}/><h3>Build isolation</h3><p>Execuções limitadas por memória, processos e timeout. Releases antigas continuam disponíveis para rollback.</p><ul><li>MemoryMax 768 MB</li><li>TasksMax 128</li><li>Timeout 600 s</li><li>Atomic release switch</li></ul></section></div>}
export default function App(){const[page,setPage]=useState('overview');const[dark,setDark]=useState(()=>localStorage.getItem('ztr-theme')!=='light');useEffect(()=>localStorage.setItem('ztr-theme',dark?'dark':'light'),[dark]);const views={overview:<Overview/>,projects:<Projects/>,deployments:<Deployments/>,analytics:<Analytics/>,settings:<SettingsPage/>};return <Shell page={page} setPage={setPage} dark={dark} setDark={setDark}>{views[page]}</Shell>}
